version: "3"
services:
  app:
    build: .
    networks:
      - backend
    environment:
      - POSTGRES_PORT=${PGPORT}
      - POSTGRES_USER=${PGUSERNAME}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${DATABASE_URL}
      - SECRET = ${SECRET}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5004
    container_name: quatrogrocernodejs
    # tty: true
    command: ["npm", "run", "dev"]
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PORT=${PGPORT}
      - POSTGRES_USER=${PGUSERNAME}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${DATABASE_URL}
    networks:
      - backend
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d/
      - ../postgres_data/:/var/lib/postgresql/data
    container_name: quatrogrocerdb
networks:
  backend:

  # Dockerfile
